language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CI=true
scripts:
  - npm install
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep_history: false
  local_dir: storybook-static
  on:
    branch: master