language: node_js
node_js:
  - 15
cache: npm
env:
  - CI=true
before_install:
  - npm config set registry http://registry.npm.taobao.org/
script:
  - npm run build-storybook
  - npm config set registry https://registry.npmjs.org/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: main